apiVersion: apps/v1
kind: Deployment
metadata:
 name: menu
spec:
 replicas: 1
 selector:
  matchLabels:
   app: menu
 template:
  metadata:
   labels:
    app: menu
  spec:
   containers:
    - name: menu
      image: josegabjimenez/forkfiesta-menu
      ports:
       - containerPort: 4000
